version: '3'

services:
  postgres:
    image: postgres:9.6.17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=horizon
    volumes:
      - ./db-data:/var/lib/postgresql/data
    network_mode: bridge

  horizon:
    image: stellar/horizon:1.12.0
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:password@host.docker.internal:5432/horizon?sslmode=disable
      - ENABLE_CAPTIVE_CORE_INGESTION=true
      - STELLAR_CORE_URL=http://127.0.0.1:11626
      - STELLAR_CORE_CONFIG_PATH=/etc/stellar/stellar-core.cfg
      - HISTORY_ARCHIVE_URLS=https://history.stellar.org/prd/core-testnet/core_testnet_001
      - NETWORK_PASSPHRASE=Test SDF Network ; September 2015
      - INGEST=true
      - PER_HOUR_RATE_LIMIT=0
    volumes:
      - ./stellar-core_captive-testnet.cfg:/etc/stellar/stellar-core.cfg
    network_mode: bridge
